#!/bin/bash
#
#SBATCH --job-name="dwnldfastq"

#SBATCH --cpus-per-task=5

#SBTACH --mem=40G

#SBATCH --partition=all

#SBATCH --output=/home/adeiturrate/out/dwnld_%j.out

#SBATCH --error=/home/adeiturrate/error/dwnld_%j.err
#############################

# This script allow you to get the fastq from NCBI. It can be use either with wget and the URL or with the prefetch and the SRA ID

module load sratoolkit/2.10.4
cd /projects/125-emmer/Wang2022_emmer_fastq

for line in $(cat /projects/125-emmer/Wang2022_emmer_fastq/SRR_codes.txt | head -n 31);
    do {
        
        Name=$(echo $line | cut -f1 -d ',')
        Url=$(echo $line | cut -f2 -d ',')
        

        echo 'downloading from' $Url 'file' $Name;
        wget -O $Name $Url;
        echo 'from sra to fastq' $Name
        fastq-dump --split-files $Name --gzip 
        rm $Name


    }; done;

module unload sratoolkit/2.10.4
